# Generated by Django 4.2.1 on 2023-05-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="time",
            field=models.IntegerField(null=True),
        ),
    ]
