# Generated by Django 4.2.1 on 2023-05-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="content",
            new_name="contenido",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="subtitle",
            new_name="subtitulo",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="title",
            new_name="titulo",
        ),
        migrations.RemoveField(
            model_name="service",
            name="time",
        ),
    ]
