# Generated by Django 4.2.1 on 2023-05-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="image",
            field=models.ImageField(upload_to="blog", verbose_name="Imagen"),
        ),
    ]
