# Generated by Django 4.2.1 on 2023-05-21 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_mesa_created_mesa_updated_reserva_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="mesa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservas.mesa",
            ),
        ),
    ]
