# Generated by Django 4.2.1 on 2023-05-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0003_alter_reserva_id_alter_reserva_mesa"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="cantidad_de_personas",
            field=models.IntegerField(default=23, max_length=10),
            preserve_default=False,
        ),
    ]
